// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vireon.DataAccessLayer.Concrete.EntityFramework;

#nullable disable

namespace Vireon.DataAccessLayer.Migrations
{
    [DbContext(typeof(VireonContext))]
    [Migration("20260404201723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "VR-1001",
                            Balance = 15000m,
                            Currency = "TRY",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "VR-1002",
                            Balance = 8500m,
                            Currency = "TRY",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "VR-1003",
                            Balance = 3200m,
                            Currency = "TRY",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.DailyLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MaxDailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsedLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DailyLimits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastResetDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxDailyLimit = 50000m,
                            UsedLimit = 1500m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastResetDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxDailyLimit = 25000m,
                            UsedLimit = 0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            LastResetDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxDailyLimit = 10000m,
                            UsedLimit = 500m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.FraudLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("FraudLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Description = "Normal işlem",
                            LogDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RiskType = "Low"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Description = "Yüksek tutarlı işlem tespit edildi",
                            LogDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RiskType = "Medium"
                        });
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("LedgerEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = -1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "VR-1002 hesabına havale",
                            NewBalance = 15000m,
                            PreviousBalance = 16000m
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "VR-1001 hesabından havale",
                            NewBalance = 8500m,
                            PreviousBalance = 7500m
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 2,
                            Amount = -500m,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "VR-1003 hesabına havale",
                            NewBalance = 8500m,
                            PreviousBalance = 9000m
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 3,
                            Amount = 500m,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "VR-1002 hesabından havale",
                            NewBalance = 3200m,
                            PreviousBalance = 2700m
                        });
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReceiverAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SenderAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverAccountId");

                    b.HasIndex("SenderAccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000m,
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverAccountId = 2,
                            SenderAccountId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            Date = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverAccountId = 3,
                            SenderAccountId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 250m,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverAccountId = 3,
                            SenderAccountId = 1
                        });
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "cavitbatu@vireon.com",
                            Name = "Cavit Batu",
                            Password = "123456",
                            Surname = "Soylu"
                        },
                        new
                        {
                            Id = 2,
                            Email = "enes@vireon.com",
                            Name = "Enes",
                            Password = "123456",
                            Surname = "Kaya"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kerem@vireon.com",
                            Name = "Kerem",
                            Password = "123456",
                            Surname = "Arslan"
                        });
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.Account", b =>
                {
                    b.HasOne("Vireon.EntityLayer.Concrete.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.DailyLimit", b =>
                {
                    b.HasOne("Vireon.EntityLayer.Concrete.User", "User")
                        .WithOne("DailyLimit")
                        .HasForeignKey("Vireon.EntityLayer.Concrete.DailyLimit", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.FraudLog", b =>
                {
                    b.HasOne("Vireon.EntityLayer.Concrete.Account", "Account")
                        .WithMany("FraudLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.LedgerEntry", b =>
                {
                    b.HasOne("Vireon.EntityLayer.Concrete.Account", "Account")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.Transaction", b =>
                {
                    b.HasOne("Vireon.EntityLayer.Concrete.Account", "ReceiverAccount")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("ReceiverAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vireon.EntityLayer.Concrete.Account", "SenderAccount")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverAccount");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.Account", b =>
                {
                    b.Navigation("FraudLogs");

                    b.Navigation("LedgerEntries");

                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");
                });

            modelBuilder.Entity("Vireon.EntityLayer.Concrete.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("DailyLimit");
                });
#pragma warning restore 612, 618
        }
    }
}
